In [10]:
 #Q1 Write a Python program to create an array of 5 integers and display the array items. 
    # Access individual element through indexes
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:
#Q2 Write a Python program to reverse the order of the items in the array
res_arr = np.flip(arr)
print(res_arr)

[5 4 3 2 1]


In [31]:
#Q3 Create a 4X2 integer array and Prints its attributes 
#The shape of an array.
#Array dimensions.
#The Length of each element of the array in bytes.
arr4_2 = np.array([[1,2],[3,4],[5,6.0],[7,18]])
print(arr4_2)
print("Shape attribute:",arr4_2.shape)
print("dimension attribute:",arr4_2.ndim)
print("Size of each element in bytes:", arr4_2.itemsize)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7. 18.]]
Shape attribute: (4, 2)
dimension attribute: 2
Size of each element in bytes: 8


In [24]:
#Q4 return array of items in the third column from all rows in the following numpy array
example_arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(example_arr)
print("\nThird column from all the rows:",example_arr[:,2])

[[11 22 33]
 [44 55 66]
 [77 88 99]]

Third column from all the rows: [33 66 99]


In [19]:
#Q5 Create a result array by adding the following two NumPy arrays
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arrayThree = arrayOne + arrayTwo
print(arrayThree)

[[20 39 33]
 [25 25 28]]


In [27]:
#Q6 Sort the previous array
sorted_arr = np.sort(arrayThree)
print(sorted_arr)
print(arrayThree)

[[20 33 39]
 [25 25 28]]
[[20 39 33]
 [25 25 28]]
